version: '3'
services:
  db:
    image: postgres:14.5-bullseye
    environment:
      DB_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
  api:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - .:/app
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - DB_USER=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
volumes:
  data: {}
